replicaCount: 1

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

image:
  repository: registry.falabella.tech/digital-retail/catalyst/osmos/relevancy/query-ranking-api

ingress:
  enabled: true
  hosts:
    - "*"

egress:
  enabled: true
  hosts:
    - "*.googleapis.com"

resources:
  requests:
    cpu: "1000m"
    memory: "3Gi"
  limits:
    memory: "4Gi"

environmentVariables:
  DD_ENV: "staging"
  DD_SERVICE: "so-stag-query-ranking-api"
  DD_LOGS_INJECTION: true
  DD_PROFILING_ENABLED: true
  DD_TRACE_ENABLED: true
  DD_TAGS: "app:query-ranking-api,country:corp,domain:search"
  HOST: "0.0.0.0"

datadog:
  env: staging
  service: "so-stag-query-ranking-api"

gcp:
  enabled: false

workloadidentity:
  enabled: true
  k8ssvcacc: relevancy-sa
